services:

  postgres:
    image: postgres:16-alpine
    container_name: devops-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped


  backend:
    build:
      context: ./backend

    container_name: devops-backend

    environment:
      APP_NAME: ${APP_NAME}
      ENVIRONMENT: ${ENVIRONMENT}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_PUBLIC_ENDPOINT_URL: ${S3_PUBLIC_ENDPOINT_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

      CORS_ORIGINS: ${CORS_ORIGINS}

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}

    container_name: devops-frontend

    ports:
      - "3000:80"

    depends_on:
      backend:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1/"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped


volumes:
  postgres_data:
